### ISSUE TITLE
500 Internal Server error while creating student using POST

### ISSUE THREAD

**Issue by borsemayur2** [mongodb-developer/mongodb-with-fastapi#1]
Versions:
python: 3.9.4

```
raise WriteConcernError(

pymongo.errors.WriteConcernError: No write concern mode named 'majorityc' found in replica set configuration, full error: {'code': 79, 'codeName': 'UnknownReplWriteConcern', 'errmsg': "No write concern mode named 'majorityc' found in replica set configuration", 'errInfo': {'writeConcern': {'w': 'majorityc', 'wtimeout': 0, 'provenance': 
'clientSupplied'}}}

```

![image](https://user-images.githubusercontent.com/47341981/116802145-4c302100-ab2e-11eb-8179-3bb9b0687425.png)

**Comment by MaBeuLux88** [comment]
Hi @borsemayur2, 

Thanks for reaching out :+1: !
Looks like you have a typo somewhere because it should be "majority", not "majorityc".
Maybe you added an extra "c" by mistake when you created the MONGODB_URL env variable?

```
export MONGODB_URL="mongodb+srv://<username>:<password>@<url>/<db>?retryWrites=true&w=majority"
```

Cheers,
Maxime.

**Comment by borsemayur2** [comment]
Yeah, quite right. It's working well. Thanks
