### ISSUE TITLE
return _id

### ISSUE THREAD

**Issue by vinnitu** [mongodb-developer/mongodb-with-fastapi#14]
https://github.com/mongodb-developer/mongodb-with-fastapi/blob/ef8e87de50ba87f6b26b2c37a410e3f5b8f7310c/app.py#L76

how to return 'id' instead of '_id'?

**Comment by judy2k** [comment]
I'm about to merge a fix that answers your question, but the short answer is that the endpoint decorator should have an argument `response_model_by_alias=False`, as in https://github.com/mongodb-developer/mongodb-with-fastapi/blob/dependency-update/app.py#L94
