### ISSUE TITLE
Does this store the id as bson or string?

### ISSUE THREAD

**Issue by philipjusher** [mongodb-developer/mongodb-with-fastapi#15]
I think this is converting the ID to string on line 73
`student = jsonable_encoder(student)`

So when you insert it creates a new field "_id" with string type and not using bson?
As I understand it's best practice for the "_id" field to be bson for performance and as it's used as the key in Mongo?

Any workaround if we want this to store as bson.

**Comment by judy2k** [comment]
Although we're converting the data to JSON to provide to the MongoDB driver, the driver will automatically convert this to BSON for you. This is true of all data you provide to PyMongo/Motor.
